BA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from website import views
from rest_framework import routers

router = routers.DefaultRouter()
app_name = 'website'

urlpatterns = [
    url(r'^$', views.homepage, name='index'),
    path('website/', include('website.urls')),
    path('admin/', admin.site.urls),

]
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        views.activate, name='activate'),
]

website/urls.py
from django.urls import path
from django.conf.urls import *
from . import views
from .views import IdeaViewSet, HistoryViewSet, OwnIdeasViewSet
from rest_framework import routers

app_name = 'website'

urlpatterns = [
    url(r'^$', views.homepage, name='index'),
    url(r'^$', HistoryViewSet.as_view, name='history'),
    url(r'^ideas/$', IdeaViewSet.as_view, name='idea-list'),
    url(r'^ideas/user/(?P<pk>\d+)/$', OwnIdeasViewSet.as_view, name='own-idea-list'),

    path('index', views.IndexView.as_view(), name='index'),
    path('history', views.HistoryView.as_view(), name='history'),
    path('ideas', views.IdeasView.as_view(), name='ideas'),
    url(r'^idea/new/$', views.idea_new, name='idea_new'),
    url(r'^idea/(?P<pk>\d+)/$', views.idea_detail, name='idea_detail'),
    path('phasergame', views.PhaserGameView.as_view(), name='phasergame'),

    # url(r'^signup/$', views.signup, name='signup'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        views.activate, name='activate'),
]

website/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from django.contrib.auth.models import AbstractUser


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    requests_left = models.IntegerField(default=1)
    votes_left = models.IntegerField(default=1)
    email_confirmed = models.BooleanField(default=False)

    @receiver(post_save, sender=User)
    def create_player(sender, instance, created, **kwargs):
        if created:
            Player.objects.create(user=instance)
        instance.player.save()

    def player_set_requests(self, new_requests):
        self.requests_left = new_requests

    def player_increase_requests(self):
        self.requests_left += 1

    def player_decrease_requests(self):
        self.requests_left -= 1

    def __str__(self):
        return self.user.username

    def current_version_beaten (self):
        ver = Version.objects.all().order_by('-id')[0]
        current = GameInfo.objects.all().filter(version=ver,user=self.user)
        return current.rounds_won >= 1


class Version(models.Model):
    label = models.CharField(max_length=20,unique=True)
    change = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=datetime.now)
    submitter = models.ForeignKey(Player, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return self.label

    def is_newest(self):
        if self == Version.objects.latest():
            return True
        return False


class Idea(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ideas')
    version = models.ForeignKey(Version, on_delete=models.CASCADE, null=True, related_name='ideas')
    request_text = models.CharField(max_length=40)
    description = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published', default=datetime.now)
    estimated_time = models.CharField(max_length=50, null=True, default='')
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    #
    # votes = models.IntegerField(default=0)
    #

    def __str__(self):
        return self.request_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def is_newest_version(self):
        ver = Version.objects.all().order_by('-id')[0]
        return self.version == ver


class GameInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gameinfo')
    version = models.ForeignKey(Version, on_delete=models.CASCADE, null=True, related_name='gameinfo')
    rounds_won = models.IntegerField(default=0)
    rounds_lost = models.IntegerField(default=0)
    enemies_killed = models.IntegerField(default=0)
    coins_collected = models.IntegerField(default=0)
    highscore = models.IntegerField(default=-1)

    def __str__(self):
        return self.version.label + '  ' + self.user.username + '  ' + self.rounds_won + ...
        '/' + (self.rounds_won + self.rounds_lost)


class WebsiteInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='websiteinfo')
    version = models.ForeignKey(Version, on_delete=models.CASCADE, null=True, related_name='websiteinfo')
    time_spent_game = models.IntegerField(default=0)
    time_spent_ideas = models.IntegerField(default=0)
    time_spent_index = models.IntegerField(default=0)
    time_spent_history = models.IntegerField(default=0)
    time_spent_chat = models.IntegerField(default=0)

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Idea, Player


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Enter a unique email address')

    class Meta:
        model = User
        help_texts = {
            'username': '',
        }
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['password1'].help_text = 'Your password must contain at least 8 characters and can not be entirely numeric'
        self.fields['password2'].help_text = None

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email


class IdeaForm(forms.ModelForm):

    class Meta:
        model = Idea
        fields = ('request_text', 'description',)

website/views.py
from .models import Idea, Version, Player
from .forms import IdeaForm, SignUpForm
from .tokens import account_activation_token
from django.shortcuts import render, redirect, render_to_response
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login, authenticate
from django.template import RequestContext
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import UserSerializer, GroupSerializer, IdeaSerializer, HistorySerializer
from .permissions import IsOwnerOrReadOnly


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all() #.order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class IdeaViewSet(viewsets.ModelViewSet):
    # ver = Version.objects.all().order_by('-pub_date')[0]
    # queryset = Idea.objects.all().filter(version=ver).order_by('-pub_date')
    queryset = Idea.objects.all()
    lookup_field = 'id'
    serializer_class = IdeaSerializer
    permission_classes = (IsOwnerOrReadOnly,)

    def pre_save(self, obj):
        obj.owner = self.request.user


class OwnIdeasViewSet(viewsets.ModelViewSet):
    serializer_class = IdeaSerializer

    def get_queryset(self):
        return Idea.objects.filter(self.request.user)


class IdeasViewSet(viewsets.ModelViewSet):
    serializer_class = IdeaSerializer

    def get_queryset(self):
        ver = Version.objects.all().order_by('-id')[0]
        return Idea.objects.filter(version=ver)


class HistoryViewSet(viewsets.ModelViewSet):
    serializer_class = HistorySerializer

    def get_queryset(self):
        return Version.objects.all()


def homepage(request):
    return render(request, 'website/home.html')

# class IndexTestView(generic.View):
#     template_name = 'website/indextest.html'
#
#     def get(self, request, *args, **kwargs):
#         return render(request, 'website/home.html')




# old views
class IndexView(generic.View):
    template_name = 'website/index.html'

    def get(self, request, *args, **kwargs):
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits+1
        version = Version.objects.all().order_by('-id')[0]
        versionLabel = version.label

        return render(request, 'website/index.html', context={
            'num_visits':num_visits, 'version':versionLabel}, # num_visits appended

    )


class HistoryView(generic.ListView):
    model = Version
    template_name = 'website/history.html'

    def get_queryset(self):
        return Version.objects.all().order_by('-pub_date')


class IdeasView(generic.ListView):
    template_name = 'website/ideas.html'
    model = Idea
    context_object_name = 'idea_list'

    def get_queryset(self):
        ver = Version.objects.all().order_by('-pub_date')[0]
        return Idea.objects.filter(version=ver).order_by('-pub_date')


class GameView(generic.View):
    template_name = 'website/game.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'website/game_alt.html')


class PhaserGameView(generic.View):
    template_name = 'website/phasergame.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'website/phasergame.html')


# @login_required()
# def idea_new(request):
#     form = IdeaForm()
#     return render(request, 'website/idea_form.html', {'form' : form})


@login_required()
def idea_new(request):
    if request.method == "POST":
        form = IdeaForm(request.POST)
        player = Player.objects.all().filter(user=request.user)[0]
        requests_left = player.requests_left
        if requests_left < 1:
            #return redirect('/website/ideas', {'vote': 'You already submited a request!'})
            return render(request, 'website/ideas.html', {'vote': 'You already '
                                                                      'submited a request this cycle!'})
        elif form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            ver = Version.objects.all().order_by('-id')[0]
            post.version = ver
            post.save()
            player.requests_left -= 1
            player.save()

            return redirect('ideas', pk=post.pk)
    else:
        form = IdeaForm()
    return render(request, 'website/idea_form.html', {'form': form})


class idea_detail(generic.DetailView):
    model = Idea
    template_name = 'website/idea.html'


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            try:
                user = form.save(commit=False)
            except Player.DoesNotExist:
                user = Player(user=request.user)
            # user.refresh_from_db()
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your Crowdjump Account'
            newuid = force_text(urlsafe_base64_encode(force_bytes(user.pk)))
            message = render_to_string('website/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                # 'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'uid': newuid,
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('website:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'website/signup.html', {'form': form}, RequestContext(request))


def account_activation_sent(request):
    return render(request, 'website/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Player.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.player.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('website:index')
    else:
        return render(request, 'website/account_activation_invalid.html')

website/templates/website/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration on Crowdjump:

http://{{ domain }}{% url 'website:activate' uidb64=uid token=token %}
{% endautoescape %}

website/templates/website/account_activation_invalid.html
{% extends 'base.html' %}

{% block container %}
  <h2>The activation of the account failed.</h2>

{% endblock %}

website/templates/website/account_activation_sent.html
{% extends 'base.html' %}

{% block container %}
  <h2>Please confirm your email address to complete the registration</h2>

{% endblock %}

website/templates/website/base.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Crowdjump{% endblock %} </title>

    {% load static %}
    {% load base_extras %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block head %}

    {% endblock %}
</head>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" date-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-Brand" href="{% url 'website:index'%}">Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class ="nav navbar-nav">
                <li class="{% active_page request "phasergame" %}">
                    <a href="{% url "website:phasergame" %}">
                        <span class="" aria-hidden="true"></span>&nbsp;Game</a>
                </li>
                <li class="{% active_page request "history" %}">
                    <a href="{% url "website:history" %}">
                        <span class="" aria-hidden="true"></span>&nbsp;History</a>
                </li><li class="{% active_page request "ideas" %}">
                    <a href="{% url "website:ideas" %}">
                        <span class="" aria-hidden="true"></span>&nbsp;Ideas</a>
                </li>
            </ul>


            <ul class ="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'website:phasergame'%}">
                        <span class="" aria-hidden="true"></span>&nbsp;Deutsch </a>
                </li>
                <li class="">
                    <a href="{% url 'website:game'%}">
                        <span class="" aria-hidden="true"></span>&nbsp; Logout </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

website/templates/website/history.html
{% extends "website/../base.html" %}
{% load static %}

{% block title %}History{% endblock %}

{% block head %}

{% endblock %}


{% block container %}
    <h1> Previous Versions and Patchnotes  </h1>
    <h4>
        Here you can find the features that got implemented, as well as the user who submitted the idea. <br>
        You want your own special feature? Submit your own on <a href="{% url "website:ideas" %}">Ideas </a><br><br>
    </h4>
{% endblock %}


{% block body %}

{% if version_list %}


    <div class="container">
        <table class="table table-striped table-hover">
            <thead class= "thead-dark">
              <tr>
                  <th scope="col">Version</th>
                  <th scope="col">Change</th>
                  <th scope="col">User</th>
                  <th scope="col">Date</th>
              </tr>
            </thead>
            <tbody>
                {% for version in version_list %}
                    <tr>
                        <td>{{ version.label }}</td>
                        <td>{{ version.change }}</td>
                        <td>{{ version.submitter.user.username}}</td>
                        <td>{{ version.pub_date}}</td>
                    </tr>
                {% endfor %}

            </tbody>

        </table>
    </div>


{% else %}
    <p>No history available.</p>
{% endif %}
{% endblock %}

website/templates/website/home.html
{% load static %}
{% load base_extras %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Crowdjump </title>
    <!-- CSS (load bootstrap) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}"/>
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular-route.js"></script>
    <script src="//unpkg.com/@uirouter/angularjs/release/angular-ui-router.min.js"></script>

    <script type="text/javascript" src="{% static 'website/js/angularroute.js' %}"></script>

    <script src="/static/website/js/phaser.js"></script>

    <script src="/static/website/js/startmenu.js"></script>
    <script src="/static/website/js/game.js"></script>
    <script src="/static/website/js/endscreen.js"></script>
    <script src="/static/website/js/boot.js"></script>
    <script src="/static/website/js/preloader.js"></script>
    <script src="/static/website/js/main.js"></script>


    {#    TODO ICON #}
    <link rel="shortcut icon" href="">
</head>

<!-- apply our angular app to our site -->
<body ng-app="app">

<!-- NAVIGATION -->
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container-fluid">

        <!-- Header -->
        <a class="navbar-brand" ui-sref="home">Home</a></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" ui-sref="game">Game</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" ui-sref="ideas">Ideas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" ui-sref="history">History</a>
                </li>
            </ul>


            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" style="color: red" ui-sref="index">{{ user.get_username }} </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">
                            <span class="fa fa-sign-out" aria-hidden="true"></span>&nbsp; Logout </a>
                    </li>
                {% else %}
                    <li class="">
                        <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">
                            <span class="" aria-hidden="true"></span>&nbsp; Login </a>

                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
<br>

<div class="container">
    <div ui-view>
    </div>

</div>


</body>
</html>

website/templates/website/idea.html
{% extends "website/../base.html" %}
{% load static %}

{% block title %}Ideas{% endblock %}

{% block head %}
    <style>
        #ideas {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 60%;
        }

        #ideas td, #ideas th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #ideas tr:nth-child(even){
            background-color: #e2e2e2;
            color:black}

        #ideas tr:hover {background-color: #ddd;}

        #ideas th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color:indianred;
            color: white;
        }

        table{
            margin: 20px;
        }
    </style
{% endblock %}
{% block body %}

    <style>
        p {margin-left: 80px;}
        a {margin-left: 30px;}
        h1 {margin-left: 80px;}
        h4 {margin-left: 80px;}

    </style>

    <h1>{{ idea.request_text }}</h1>
    <ul>
        <p>{{ idea.description }}</p>
    </ul>
 {% if user.is_authenticated %}
     <a style="font-size: 20px" href="{% url 'website:idea_form'%}"> Change </a>
     <a style="font-size: 20px" href="{% url 'website:idea_form'%}"> Delete </a>
 {% else %}
     <a style="font-size: 30px" href="{% url 'login'%}">Login to submit your own Idea!</a>
 {% endif %}


{% endblock %}

website/templates/website/idea_form.html
{% extends "website/../base.html" %}
{% load static %}

{% block title %}Submit Idea{% endblock %}

{% block container %}
<form method="post" novalidate>
  {% csrf_token %}
  <table class="table" border="1">
      <thead>
        <div class="container">
            <h1>Submit your idea here!</h1> <br>

        </div>
      </thead>
      <tbody>
      <tr>
          {{ form }}
         <!-- <input type="hidden" name="user" value="{{ user}}"> -->
      </tr>
      </tbody>
  </table>
    <div class="container">
        <button class="btn btn-info" type="submit">Submit</button>

    </div>
</form>
   <!-- 'You already submitted a request! Do you want to delete it?' -->


{% endblock %}

website/templates/website/ideas.html
{% extends "website/../base.html" %}
{% load static %}

{% block title %}Ideas{% endblock %}

{% block head %}

{% endblock %}
{% block body %}
{#<link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}" />#}

<div class="container" >

    <h1> Current Ideas  </h1>

    <h4>
        Here are the current ideas for new features, all submitted by players like you! <br>
        At the moment, every X days a random request will be implemented. If you want to have more control
        over the selection process, feature requests are not limited to the game but can also include
        communication or voting features! <br>
        Every request cycle you can submit one idea, you will be notified when a new cycle starts.
        The estimated time is edited manually may help you to find suited ideas. <br><br>

        Current state of the game:<br><br>
        <div class="container" style = "margin-left: 7px">
            <ul class="list-group">

                <li class="list-group-item list-group-item-danger">
                    Just a very simple plattformer. You could request more game related features!
                </li>
                <li class="list-group-item list-group-item-danger">
                    The game is black, white and not that pretty. Maybe design requests would help!
                </li>
                <li class="list-group-item list-group-item-danger">
                    Random ideas are chosen. If you want to request an idea as a community (or maybe just push your own),
                     you should think of ways to organize the requests!
                </li>
                <li class="list-group-item list-group-item-danger">
                    There is not much on the website. If you have ideas to alter the website, submit them!
                </li>
            </ul>
            {% if vote %}
                <h1><br>{{ vote }}</h1>
            {% endif %}
        </div>
    </h4> <br> <br>
    <div class="alert alert-info">
        <strong>
            {% if user.is_authenticated %}
                 <a style="font-size: 28px" style="margin-left: 90px" href="{% url 'website:idea_new'%}"> Submit your own Idea! </a>
            {% else %}
                 <a style="font-size: 28px" style="margin-top: 45px" href="{% url 'login'%}?next={{request.path}}">Login to submit your own Idea!</a>
            {% endif %}
        </strong>
    </div>

</div>


{% if idea_list %}

<div class="container">
  <table class="table table-striped table-hover">
    <thead class= "thead-dark">
      <tr>
        <th scope="col">Version</th>
        <th scope="col">Request</th>
        <th scope="col">User</th>
        <th scope="col">Date</th>
        <th scope="col">Estimated Time</th>
      </tr>
    </thead>
    <tbody>
    {% for idea in idea_list %}
      <tr>
        <th>{{ idea.version.label }}</th>
        <td>{{ idea.description }}</td>
        <td>{{ idea.user.username}}</td>
        <td>{{ idea.pub_date}}</td>
        <td>{{ idea.estimated_time}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
{#    <p>No ideas available.</p>#}
{% endif %}
{% endblock %}

website/templates/website/index.html
{% extends "website/../base.html" %}


{% load static %}

{% block head %}
{% endblock %}

{% block jumbo %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
        <img class="img-fluid" src="{% static 'website/images/logo.png' %}" alt="Crowdjump">
        <h1>Welcome to Crowdjump!</h1>
        <h3> Version {{ version }}</h3>
    </div>
  </div>
{% endblock %}


{% block container %}

<h4> Crowdjump is a bachelor thesis in which you can submit your ideas to improve a simple game to your likings!<br><br>
     The goal of the thesis is to observe how a game is designed bottom-up with a crowd and how the decision finding<br>
     process is made. <br><br><br>


    The game itself can be found at
    <div class="btn-group">
        <a href="{% url "website:phasergame" %}" class="btn btn-info">
            <i aria-hidden="true"></i> Game
        </a>
    </div> <br><br>

    If you played the game and want to submit a new feature, you should visit
    <div class="btn-group">
        <a href="{% url "website:ideas" %}" class="btn btn-info">
            <i aria-hidden="true"></i> Ideas
        </a>
    </div> <br><br>

    On
    <div class="btn-group">
        <a href="{% url "website:history" %}" class="btn btn-info">
            <i aria-hidden="true"></i> History
        </a>
    </div>
    you can find the changes implemented in previous iterations of the game.

</h4>
<article>
</article>

{% endblock %}

website/templates/website/newsletter_form.html
Hi {{ user.username }},

Please click on the link below to confirm your registration on Crowdjump:

https://crowdjump.win{% url 'website:game' %}

website/templates/website/password_reset_confirm.html
{% extends "base.html" %}

{% block body %}

    {% if validlink %}
        <p>Please enter (and confirm) your new password.</p>
        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}

{% endblock %}